FROM slicer/slicer-base:latest

LABEL maintainer="3D Slicer Community <slicer-devel@bwh.harvard.edu>"

RUN \
  #
  # Re-configure
  #
  cd /usr/src/Slicer-build && \
  cmake -DBUILD_TESTING:BOOL=OFF . && \
  #
  # Build
  #
  /usr/src/Slicer-build/BuildSlicer.sh && \
  #
  # Cleanup
  #
  cd /usr/src/Slicer-build/Slicer-build && \
  find . -name '*.o' -delete && \
  find lib -name '*.a' -delete && \
  rm -rf _CPack_Packages

WORKDIR /usr/src/Slicer-build/Slicer-build

CMD bash

#include "common.label-and-env"
